[project]
name = "chonkie-140-error"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chonkie>=1.4.0",
    "django>=5.2.7",
    "requests>=2.32.5",
    "typing-extensions>=4.15.0",
]
